### ISSUE TITLE
Setup Google Analytics.

### ISSUE THREAD

**Issue by proofit404** [dry-python/dry-python.github.io#2]

**Comment by proofit404** [comment]
https://github.com/lektor/lektor-website/ has a useful example.

**Comment by supadrupa** [comment]
[https://www.getlektor.com/plugins/lektor-google-analytics/](https://www.getlektor.com/plugins/lektor-google-analytics/
) has a plugin.

**Comment by proofit404** [comment]
Hi!
Thanks for the helpful info!
Sources look straightforward.
I think we could start to use it.
Can I assign this issue to you?
Best regards, Artem.

**Comment by supadrupa** [comment]
> Can I assign this issue to you?

yep, i will do it

**Comment by supadrupa** [comment]
I need you google analytics id `GOOGLE_ANALYTICS_ID = UA-XXXXXXXX-Y`
