### ISSUE TITLE
Layout problems on low width displays

### ISSUE THREAD

**Issue by Roxe322** [dry-python/dry-python.github.io#34]
Hello! In mobile devices with low screen resolution layout of your site looks not very good. In my opinion only on 570px width and more it looks like were expected. 

![image](https://user-images.githubusercontent.com/38218668/56348842-fe0e8600-61cf-11e9-89ed-35551c3760c3.png)
![image](https://user-images.githubusercontent.com/38218668/56348862-0666c100-61d0-11e9-8a65-ab7268a6d629.png)

**Comment by proofit404** [comment]
Fixed by #325
